matrix:
  include:
    - language: python
      sudo: required
      dist: xenial
      python: "3.6.7"
      cache: 
        pip: true
      before_install:
        - cd sentinel_connectors
      install:
        - make requirements
      script:
        - make tests
        - make lint
  include:
    - language: node_js
      node_js:
        - 12.2
      before_install:
        - cd sentinel_web
      install:
        - yarn install