matrix:
  include:
    - language: python
      env: COMMAND=sentinel_connectors
      sudo: required
      dist: xenial
      python: "3.6.7"
      cache: 
        pip: true
      before_install:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(sentinel_connectors/|sentinel_common/|\.travis.yml)' || exit 0
        - cd sentinel_connectors
      install:
        - make requirements
      script:
        - make tests
        - make lint

    - language: python
      env: COMMAND=sentinel_backend
      sudo: required
      dist: xenial
      python: "3.6.7"
      cache: 
        pip: true
      before_install:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(sentinel_backend/|sentinel_common/|\.travis.yml)' || exit 0
        - cd sentinel_backend
      install:
        - make venv
      script:
        - make lint
      
    - language: python
      env: COMMAND=sentinel_lambda
      sudo: required
      dist: xenial
      python: "3.6.7"
      cache: 
        directories:
          - node_modules
        pip: true
      before_install:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(sentinel_lambda/|sentinel_common/|\.travis.yml)' || exit 0
        - cd sentinel_lambda
        - nvm install 6
        - node --version
        - npm --version
      install:
        - cd sentinel-analizer
        - npm install -g serverless
        - npm install --save serverless-python-requirements
      script:
        
      after_script:
        - cd sentinel-analizer
        - test $TRAVIS_BRANCH = "feature/sentinel_lambda_ci" && test $TRAVIS_PULL_REQUEST = "false" && serverless deploy -v --aws-s3-accelerate

    - language: node_js
      env: COMMAND=sentinel_web
      node_js:
        - 12.2
      before_install:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(sentinel_web/|sentinel_common/|\.travis.yml)' || exit 0
        - cd sentinel_web
      install:
        - yarn install
      script:
        - yarn build