#!/bin/bash
declare -a topics=("google-news" "hacker-news" "reddit" "twitter")
export AWS_DEFAULT_REGION=eu-central-1
export DYNAMO_DB_REGION=eu-central-1
echo -e '\nexport AWS_DEFAULT_REGION=eu-central-1' >> ~/.bashrc

cd /home/ec2-user/sentinel/sentinel_connectors
source .env/bin/activate

echo Starting producers...
for topic in "${topics[@]}"; do
    echo Starting $topic producer
    python3.6 run_connector.py stream --source $topic --sink kinesis > /dev/null 2>&1 &
done